namespace Webora.Application.Parking;

/// <summary>The editable parking and incentive settings.</summary>
public sealed record ParkingSettingsDto(
    int ReleasePoints,
    int OffPeakBonusPoints,
    int NoShowPenaltyPoints,
    TimeSpan ReleaseCutoff,
    TimeSpan NoShowGracePeriod,
    TimeSpan ReminderLeadTime,
    TimeOnly PeakStart,
    TimeOnly PeakEnd,
    TimeSpan SweepInterval,
    TimeOnly ResidentHoldUntil,
    int ResidentReleasePointsPerHour,
    int ResidentReleaseMaxPoints,
    int ResidentMaxShareAllowance,
    int ResidentSharePercentPerAllowance,
    int ResidentWastedShareClawbackPercent,
    double? LotLatitude,
    double? LotLongitude,
    int SharedTakenBasePoints,
    int SharedTakenReferenceKm,
    int SharedTakenMaxMultiplier,
    bool AutoVerifyHomeAddress,
    int AutoVerifyMaxDistanceKm,
    int MaxRewardedReleasesPerDay,
    int MaxReleaseRangeDays,
    int BaseReservationCost,
    int PeakPricePercent,
    int OccupancyPricePercent,
    int MaxReservationCost,
    int MonthlyCreditAllowance,
    int QueueOfferMinutes);
