<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <ProjectReference Include="..\Webora.Web.Client\Webora.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Webora.Infrastructure\Webora.Infrastructure.csproj" />
    <ProjectReference Include="..\Webora.Application\Webora.Application.csproj" />
  </ItemGroup>

</Project>
